Fix crash when using Realm 4.2.0
This is due to `SharedRealm` has been renamed to `OsSharedRealm` causing a NoClassDefFoundError  
https://github.com/realm/realm-java/commits/master/realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java